Add TransactionList and TransactionItem components
argentlabs/Starknet-Scaffold pull request #16
Opened 2024-02-18 20:39 UTC by Cheelax

## Description

Implementation of a component to list transactions

## Additional Information

- [X] I have read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [X] This is not a duplicate of any [existing pull request](https://github.com/argentlabs/Starknet-Scaffold/pulls)

## Related Issues

_Closes #4

2024-02-18 23:37 UTC, Darlington02 requested changes
Great job @Cheelax! let's have a little icon that shows up close to the address bar. This icon should only show up once a user connects his wallet and when clicked should pop up the transaction tracker modal.

2024-02-18 23:44 UTC, Darlington02 requested changes

2024-02-18 23:44 UTC, Darlington02 commented on package.json
> +    "lucide-react": "^0.331.0",
please all ui related dependencies should go into the `frontend` folder. The base package.json shouldn't hold this dependency

2024-02-19 08:15 UTC, Cheelax commented
> @Cheelax please check why deployment fails, and try to resolve existing conflicts

Yes no problem I am still working on improving the code :)

2024-02-19 09:18 UTC, Darlington02 approved these changes

2024-02-19 10:04 UTC, merged